_wandb:
    value:
        cli_version: 0.22.2
        e:
            4dmeh8hhsa77vhgsoo6jxqacsa410t7a:
                args:
                    - --config
                    - config_training.yaml
                codePath: scripts\train.py
                codePathLocal: scripts\train.py
                email: 2630862330@qq.com
                executable: C:\Users\26308\.conda\envs\diffusers\python.exe
                git:
                    commit: f9e90b30c419d7c501e40ded86648442a2b7d4ee
                    remote: https://github.com/EGAII/condsar.git
                host: EGAIPC
                os: Windows-10-10.0.26100-SP0
                program: D:\condsar\scripts\train.py
                python: CPython 3.10.19
                root: D:\condsar
                startedAt: "2025-11-16T22:40:44.170834Z"
                writerId: 4dmeh8hhsa77vhgsoo6jxqacsa410t7a
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "2":
                - 1
                - 11
                - 41
                - 49
                - 71
                - 83
            "3":
                - 13
            "4": 3.10.19
            "5": 0.22.2
            "6": 4.57.1
            "8":
                - 3
            "10":
                - 20
            "12": 0.22.2
            "13": windows-amd64
